name: Remote Desktop GitHub Action

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t remote-desktop:latest .
        
    - name: Start Docker container
      run: |
        docker run -d -p 4040:4040 --name=rd_container remote-desktop:latest tail -f /dev/null

    - name: Setup tmate session
      run: |
        docker exec rd_container bash -c "tmate -S /tmp/tmate.sock new-session -d &"
        sleep 10
        TMATE_SSH=$(docker exec rd_container bash -c "tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'")
        echo "TMATE_SSH=$TMATE_SSH" >> $GITHUB_ENV
        TMATE_WEB=$(docker exec rd_container bash -c "tmate -S /tmp/tmate.sock display -p '#{tmate_web}'")
        echo "TMATE_WEB=$TMATE_WEB" >> $GITHUB_ENV

    - name: Show tmate connection details
      run: |
        echo "SSH connection: $TMATE_SSH"
        echo "Web connection: $TMATE_WEB"

    - name: Setup xrdp
      run: |
        docker exec rd_container bash -c "/etc/init.d/xrdp start"

    - name: Start ngrok tunnel
      run: |
        echo "Starting ngrok tunnel..."
        docker exec rd_container bash -c "ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}"
        docker exec rd_container bash -c "ngrok tcp 3389 &"
        sleep 10
        NGROK_URL=$(curl --silent --show-error localhost:4040/api/tunnels | jq '.tunnels[0].public_url')
        if [ -z "$NGROK_URL" ]; then
          echo "Failed to get ngrok URL"
          exit 1
        fi
        echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV

    - name: Show ngrok connection details
      run: |
        echo "RDP connection: $NGROK_URL"

    - name: Keep Action running
      run: |
        while true; do
          echo "Keeping GitHub Action running..."
          sleep 300
        done
